- name: add hhvm apt-key
  apt_key: url=http://dl.hhvm.com/conf/hhvm.gpg.key state=present
  sudo: yes

- name: add hhvm deb
  apt_repository: repo="deb http://dl.hhvm.com/ubuntu trusty main"
  sudo: yes

- name: install hhvm
  apt: pkg=hhvm
  sudo: yes
