- name: add hhvm apt-key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=0x5a16e7281be7a449 state=present
  sudo: yes

- shell: lsb_release -sc
  register: ubuntu_release_code_name

- name: add hhvm deb
  apt_repository: repo="deb http://dl.hhvm.com/ubuntu {{ ubuntu_release_code_name.stdout }} main"
  sudo: yes

- name: install hhvm
  apt: pkg=hhvm
  sudo: yes