- name: install varnish
  apt: pkg=varnish
  sudo: yes

- name: Create varnish config service
  template:
    src: default.vcl.j2
    dest: /etc/varnish/default.vcl
  sudo: yes

- name: Create varnish service
  template:
    src: varnish.service.j2
    dest: /lib/systemd/system/bloghhvm.service
  sudo: yes
  notify: Restart varnish

